inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - "bin/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/schema.rb"

Layout/SpaceInsideParens:
  EnforcedStyle: space

Style/MethodCallWithArgsParentheses:
  EnforcedStyle: require_parentheses

Style/StringLiterals:
  EnforceStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforceStyle: double_quotes
