inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

require:
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - "bin/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/schema.rb"

Layout/SpaceInsideParens:
  EnforcedStyle: space

Style/MethodCallWithArgsParentheses:
  EnforcedStyle: require_parentheses

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
