services:
  api:
    container_name: events_api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8700:80"
    volumes:
      - ./:/home/app/webapp
    networks:
      - localstack_network

volumes:
  data:
    driver: local

networks:
  localstack_network:
    external: true
