services:
  api:
    container_name: events_api
    environment:
      - RAILS_ENV=development
      - LOG_LEVEL=debug
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=datacite
      - MYSQL_HOST=lupo_mysql
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - ES_HOST=lupo_opensearch
      - ES_PORT=9200
      - ES_SCHEME=http
      - ELASTIC_PASSWORD=AnUnsecurePassword123
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DISABLE_QUEUE_WORKER=false
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8700:80"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./db:/home/app/webapp/db
      - ./lib:/home/app/webapp/lib
      - ./spec:/home/app/webapp/spec
      - ./storage:/home/app/webapp/storage
      - ./tmp:/home/app/webapp/tmp
      - bundle_cache:/home/app/webapp/vendor/bundle
      - ./Gemfile:/home/app/webapp/Gemfile
      - ./Gemfile.lock:/home/app/webapp/Gemfile.lock
    networks:
      - localstack_network
    dns:
      - 10.0.2.20

volumes:
  bundle_cache:
  gemfile:
  data:
    driver: local

networks:
  localstack_network:
    external: true
