name: Deploy Main to Staging
on:
  push:
    branches:
      - "master"
jobs:
  lint:
    uses: ./.github/workflows/rubocop.yml
  test:
    uses: ./.github/workflows/parallel_ci.yml
    secrets: inherit
  call_build_and_push:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      image_name: ${{ github.repository }}
      image_tag: main
    secrets: inherit
  deploy:
    needs: [test, call_build_and_push]
    uses: ./.github/workflows/_update_terraform.yml
    with:
      image_tag: main
      deployment_environment: staging
    secrets: inherit
