name: Parallel CI
on:
  workflow_call:
    secrets:
      SECRET_KEY_BASE:
        required: true
      SESSION_ENCRYPTED_COOKIE_SALT:
        required: true
      JWT_PRIVATE_KEY:
        required: true
      JWT_PUBLIC_KEY:
        required: true
      MDS_USERNAME:
        required: true
      MDS_PASSWORD:
        required: true
      AWS_REGION:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  parallel-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    services:
      mysql:
        image: mysql:8.0.36
        env:
          MYSQL_DATABASE: datacite
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306
      elasticsearch:
        image: opensearchproject/opensearch:2
        env:
          discovery.type: single-node
          OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
          OPENSEARCH_INITIAL_ADMIN_PASSWORD: AnUnsecurePassword123
          DISABLE_SECURITY_PLUGIN: true
          http.cors.enabled: true
          bootstrap.memory_lock: true
          http.cors.allow-origin: "*"
          compatibility.override_main_response_version: true
          logger.org.opensearch.discovery: "ERROR"
        ports:
          - 9200
    env:
      MYSQL_HOST: "127.0.0.1"
      MYSQL_DATABASE: datacite
      MYSQL_USER: root
      ES_HOST: "localhost:9200"
      ELASTIC_PASSWORD: "AnUnsecurePassword123"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.1.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.6"
          bundler-cache: true

      - name: Run Specs
        run: bundle exec rspec
