name: Test and Lint Pull Request
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/rubocop.yml
  parallel-test:
    needs: lint
    uses: ./.github/workflows/parallel_ci.yml
    secrets: inherit
